/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Parcel } from "./Parcel";
import { ParcelCountArgs } from "./ParcelCountArgs";
import { ParcelFindManyArgs } from "./ParcelFindManyArgs";
import { ParcelFindUniqueArgs } from "./ParcelFindUniqueArgs";
import { DeleteParcelArgs } from "./DeleteParcelArgs";
import { ParcelService } from "../parcel.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Parcel)
export class ParcelResolverBase {
  constructor(
    protected readonly service: ParcelService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Parcel",
    action: "read",
    possession: "any",
  })
  async _parcelsMeta(
    @graphql.Args() args: ParcelCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Parcel])
  @nestAccessControl.UseRoles({
    resource: "Parcel",
    action: "read",
    possession: "any",
  })
  async parcels(@graphql.Args() args: ParcelFindManyArgs): Promise<Parcel[]> {
    return this.service.parcels(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Parcel, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Parcel",
    action: "read",
    possession: "own",
  })
  async parcel(
    @graphql.Args() args: ParcelFindUniqueArgs
  ): Promise<Parcel | null> {
    const result = await this.service.parcel(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Parcel)
  @nestAccessControl.UseRoles({
    resource: "Parcel",
    action: "delete",
    possession: "any",
  })
  async deleteParcel(
    @graphql.Args() args: DeleteParcelArgs
  ): Promise<Parcel | null> {
    try {
      return await this.service.deleteParcel(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
